# Generated by Django 4.1 on 2022-08-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_member_created_at_remove_member_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
    ]
