# Generated by Django 4.1 on 2022-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=10)),
                ('artist_name', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('artist_intro', models.TextField(max_length=300)),
                ('post_intro', models.TextField(max_length=300)),
                ('post_plan', models.TextField()),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'post',
                'db_table': 'post',
            },
        ),
    ]
