# Generated by Django 4.0.4 on 2022-08-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_post_category_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
